# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inmoovform.ui'
#
# Created: Fri Sep 25 07:37:25 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_inmoovform(object):
    def setupUi(self, inmoovform):
        inmoovform.setObjectName(_fromUtf8("inmoovform"))
        inmoovform.setEnabled(True)
        inmoovform.resize(935, 700)
        inmoovform.setDocumentMode(False)
        inmoovform.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralWidget = QtGui.QWidget(inmoovform)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 931, 651))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Control = QtGui.QWidget()
        self.Control.setObjectName(_fromUtf8("Control"))
        self.labelmouth = QtGui.QLabel(self.Control)
        self.labelmouth.setGeometry(QtCore.QRect(629, 77, 31, 30))
        self.labelmouth.setObjectName(_fromUtf8("labelmouth"))
        self.label_36 = QtGui.QLabel(self.Control)
        self.label_36.setGeometry(QtCore.QRect(490, 59, 71, 20))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.imagerobot = QtGui.QLabel(self.Control)
        self.imagerobot.setGeometry(QtCore.QRect(110, 40, 668, 550))
        self.imagerobot.setText(_fromUtf8(""))
        self.imagerobot.setPixmap(QtGui.QPixmap(_fromUtf8("../Maya Robot/robot.png")))
        self.imagerobot.setObjectName(_fromUtf8("imagerobot"))
        self.motionRec = QtGui.QPushButton(self.Control)
        self.motionRec.setGeometry(QtCore.QRect(660, 0, 61, 27))
        self.motionRec.setCheckable(False)
        self.motionRec.setAutoDefault(False)
        self.motionRec.setDefault(False)
        self.motionRec.setFlat(False)
        self.motionRec.setObjectName(_fromUtf8("motionRec"))
        self.motionPlay = QtGui.QPushButton(self.Control)
        self.motionPlay.setGeometry(QtCore.QRect(800, 0, 61, 27))
        self.motionPlay.setObjectName(_fromUtf8("motionPlay"))
        self.motionStop = QtGui.QPushButton(self.Control)
        self.motionStop.setGeometry(QtCore.QRect(730, 0, 61, 27))
        self.motionStop.setObjectName(_fromUtf8("motionStop"))
        self.label_58 = QtGui.QLabel(self.Control)
        self.label_58.setGeometry(QtCore.QRect(740, 590, 91, 17))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.connection = QtGui.QLabel(self.Control)
        self.connection.setGeometry(QtCore.QRect(830, 590, 91, 17))
        self.connection.setObjectName(_fromUtf8("connection"))
        self.checkRightHand = QtGui.QCheckBox(self.Control)
        self.checkRightHand.setGeometry(QtCore.QRect(360, 3, 101, 22))
        self.checkRightHand.setChecked(True)
        self.checkRightHand.setObjectName(_fromUtf8("checkRightHand"))
        self.checkLeftHand = QtGui.QCheckBox(self.Control)
        self.checkLeftHand.setGeometry(QtCore.QRect(470, 3, 101, 22))
        self.checkLeftHand.setChecked(True)
        self.checkLeftHand.setObjectName(_fromUtf8("checkLeftHand"))
        self.checkHead = QtGui.QCheckBox(self.Control)
        self.checkHead.setGeometry(QtCore.QRect(570, 3, 71, 22))
        self.checkHead.setObjectName(_fromUtf8("checkHead"))
        self.label_51 = QtGui.QLabel(self.Control)
        self.label_51.setGeometry(QtCore.QRect(714, 30, 51, 17))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.statusMotion = QtGui.QLabel(self.Control)
        self.statusMotion.setGeometry(QtCore.QRect(774, 30, 67, 17))
        self.statusMotion.setObjectName(_fromUtf8("statusMotion"))
        self.label_52 = QtGui.QLabel(self.Control)
        self.label_52.setGeometry(QtCore.QRect(10, 6, 51, 17))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.romoplate = QtGui.QSlider(self.Control)
        self.romoplate.setGeometry(QtCore.QRect(365, 190, 31, 111))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.romoplate.sizePolicy().hasHeightForWidth())
        self.romoplate.setSizePolicy(sizePolicy)
        self.romoplate.setMinimum(20)
        self.romoplate.setMaximum(80)
        self.romoplate.setProperty("value", 20)
        self.romoplate.setSliderPosition(20)
        self.romoplate.setOrientation(QtCore.Qt.Vertical)
        self.romoplate.setObjectName(_fromUtf8("romoplate"))
        self.labelromoplate = QtGui.QLabel(self.Control)
        self.labelromoplate.setGeometry(QtCore.QRect(365, 293, 31, 30))
        self.labelromoplate.setObjectName(_fromUtf8("labelromoplate"))
        self.label_6 = QtGui.QLabel(self.Control)
        self.label_6.setGeometry(QtCore.QRect(370, 310, 16, 61))
        self.label_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_6.setFrameShadow(QtGui.QFrame.Plain)
        self.label_6.setMidLineWidth(0)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(False)
        self.label_6.setMargin(0)
        self.label_6.setOpenExternalLinks(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.rshoulder = QtGui.QSlider(self.Control)
        self.rshoulder.setGeometry(QtCore.QRect(331, 173, 31, 111))
        self.rshoulder.setMaximum(180)
        self.rshoulder.setSliderPosition(30)
        self.rshoulder.setOrientation(QtCore.Qt.Vertical)
        self.rshoulder.setTickPosition(QtGui.QSlider.NoTicks)
        self.rshoulder.setObjectName(_fromUtf8("rshoulder"))
        self.labelrshoulder = QtGui.QLabel(self.Control)
        self.labelrshoulder.setGeometry(QtCore.QRect(332, 283, 31, 20))
        self.labelrshoulder.setObjectName(_fromUtf8("labelrshoulder"))
        self.label_12 = QtGui.QLabel(self.Control)
        self.label_12.setGeometry(QtCore.QRect(340, 300, 16, 81))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.rrotate = QtGui.QSlider(self.Control)
        self.rrotate.setGeometry(QtCore.QRect(306, 146, 31, 111))
        self.rrotate.setMaximum(180)
        self.rrotate.setProperty("value", 90)
        self.rrotate.setOrientation(QtCore.Qt.Vertical)
        self.rrotate.setTickPosition(QtGui.QSlider.NoTicks)
        self.rrotate.setObjectName(_fromUtf8("rrotate"))
        self.labelrrotate = QtGui.QLabel(self.Control)
        self.labelrrotate.setGeometry(QtCore.QRect(306, 257, 31, 17))
        self.labelrrotate.setObjectName(_fromUtf8("labelrrotate"))
        self.label_13 = QtGui.QLabel(self.Control)
        self.label_13.setGeometry(QtCore.QRect(314, 264, 16, 81))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.rbiceps = QtGui.QSlider(self.Control)
        self.rbiceps.setGeometry(QtCore.QRect(282, 142, 20, 111))
        self.rbiceps.setMinimum(5)
        self.rbiceps.setMaximum(90)
        self.rbiceps.setOrientation(QtCore.Qt.Vertical)
        self.rbiceps.setObjectName(_fromUtf8("rbiceps"))
        self.labelrbiceps = QtGui.QLabel(self.Control)
        self.labelrbiceps.setGeometry(QtCore.QRect(277, 252, 31, 17))
        self.labelrbiceps.setObjectName(_fromUtf8("labelrbiceps"))
        self.label_14 = QtGui.QLabel(self.Control)
        self.label_14.setGeometry(QtCore.QRect(284, 263, 21, 61))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.rpalm = QtGui.QSlider(self.Control)
        self.rpalm.setGeometry(QtCore.QRect(190, 150, 21, 111))
        self.rpalm.setOrientation(QtCore.Qt.Vertical)
        self.rpalm.setObjectName(_fromUtf8("rpalm"))
        self.labelrpalm = QtGui.QLabel(self.Control)
        self.labelrpalm.setGeometry(QtCore.QRect(185, 261, 31, 17))
        self.labelrpalm.setObjectName(_fromUtf8("labelrpalm"))
        self.label_15 = QtGui.QLabel(self.Control)
        self.label_15.setGeometry(QtCore.QRect(191, 280, 21, 71))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.rfingers3 = QtGui.QSlider(self.Control)
        self.rfingers3.setGeometry(QtCore.QRect(90, 120, 29, 160))
        self.rfingers3.setMaximum(180)
        self.rfingers3.setSliderPosition(90)
        self.rfingers3.setOrientation(QtCore.Qt.Vertical)
        self.rfingers3.setObjectName(_fromUtf8("rfingers3"))
        self.rfingers5 = QtGui.QSlider(self.Control)
        self.rfingers5.setGeometry(QtCore.QRect(138, 150, 29, 160))
        self.rfingers5.setMaximum(180)
        self.rfingers5.setSliderPosition(90)
        self.rfingers5.setOrientation(QtCore.Qt.Vertical)
        self.rfingers5.setObjectName(_fromUtf8("rfingers5"))
        self.rfingers1 = QtGui.QSlider(self.Control)
        self.rfingers1.setGeometry(QtCore.QRect(40, 80, 29, 160))
        self.rfingers1.setMaximum(180)
        self.rfingers1.setSliderPosition(90)
        self.rfingers1.setOrientation(QtCore.Qt.Vertical)
        self.rfingers1.setObjectName(_fromUtf8("rfingers1"))
        self.rfingers2 = QtGui.QSlider(self.Control)
        self.rfingers2.setGeometry(QtCore.QRect(65, 110, 29, 160))
        self.rfingers2.setMaximum(180)
        self.rfingers2.setSliderPosition(90)
        self.rfingers2.setOrientation(QtCore.Qt.Vertical)
        self.rfingers2.setObjectName(_fromUtf8("rfingers2"))
        self.rfingers4 = QtGui.QSlider(self.Control)
        self.rfingers4.setGeometry(QtCore.QRect(114, 140, 29, 160))
        self.rfingers4.setMaximum(180)
        self.rfingers4.setSliderPosition(90)
        self.rfingers4.setOrientation(QtCore.Qt.Vertical)
        self.rfingers4.setObjectName(_fromUtf8("rfingers4"))
        self.lomoplate = QtGui.QSlider(self.Control)
        self.lomoplate.setGeometry(QtCore.QRect(500, 190, 31, 111))
        self.lomoplate.setMinimum(20)
        self.lomoplate.setMaximum(80)
        self.lomoplate.setProperty("value", 20)
        self.lomoplate.setSliderPosition(20)
        self.lomoplate.setOrientation(QtCore.Qt.Vertical)
        self.lomoplate.setObjectName(_fromUtf8("lomoplate"))
        self.labellomoplate = QtGui.QLabel(self.Control)
        self.labellomoplate.setGeometry(QtCore.QRect(501, 295, 31, 30))
        self.labellomoplate.setObjectName(_fromUtf8("labellomoplate"))
        self.lshoulder = QtGui.QSlider(self.Control)
        self.lshoulder.setGeometry(QtCore.QRect(536, 173, 21, 111))
        self.lshoulder.setMaximum(180)
        self.lshoulder.setSliderPosition(30)
        self.lshoulder.setObjectName(_fromUtf8("lshoulder"))
        self.labellshoulder = QtGui.QLabel(self.Control)
        self.labellshoulder.setGeometry(QtCore.QRect(532, 275, 31, 30))
        self.labellshoulder.setObjectName(_fromUtf8("labellshoulder"))
        self.lrotate = QtGui.QSlider(self.Control)
        self.lrotate.setGeometry(QtCore.QRect(563, 146, 21, 111))
        self.lrotate.setMinimum(0)
        self.lrotate.setMaximum(180)
        self.lrotate.setProperty("value", 90)
        self.lrotate.setOrientation(QtCore.Qt.Vertical)
        self.lrotate.setObjectName(_fromUtf8("lrotate"))
        self.labelrotate = QtGui.QLabel(self.Control)
        self.labelrotate.setGeometry(QtCore.QRect(560, 260, 31, 17))
        self.labelrotate.setObjectName(_fromUtf8("labelrotate"))
        self.lbiceps = QtGui.QSlider(self.Control)
        self.lbiceps.setGeometry(QtCore.QRect(590, 141, 21, 111))
        self.lbiceps.setMinimum(5)
        self.lbiceps.setMaximum(90)
        self.lbiceps.setOrientation(QtCore.Qt.Vertical)
        self.lbiceps.setObjectName(_fromUtf8("lbiceps"))
        self.labellbiceps = QtGui.QLabel(self.Control)
        self.labellbiceps.setGeometry(QtCore.QRect(586, 250, 31, 17))
        self.labellbiceps.setObjectName(_fromUtf8("labellbiceps"))
        self.lpalm = QtGui.QSlider(self.Control)
        self.lpalm.setGeometry(QtCore.QRect(680, 150, 21, 111))
        self.lpalm.setOrientation(QtCore.Qt.Vertical)
        self.lpalm.setObjectName(_fromUtf8("lpalm"))
        self.labellpalm = QtGui.QLabel(self.Control)
        self.labellpalm.setGeometry(QtCore.QRect(675, 265, 31, 17))
        self.labellpalm.setObjectName(_fromUtf8("labellpalm"))
        self.lfingers5 = QtGui.QSlider(self.Control)
        self.lfingers5.setGeometry(QtCore.QRect(718, 155, 29, 160))
        self.lfingers5.setMaximum(180)
        self.lfingers5.setSliderPosition(90)
        self.lfingers5.setOrientation(QtCore.Qt.Vertical)
        self.lfingers5.setObjectName(_fromUtf8("lfingers5"))
        self.lfingers4 = QtGui.QSlider(self.Control)
        self.lfingers4.setGeometry(QtCore.QRect(750, 145, 29, 160))
        self.lfingers4.setMaximum(180)
        self.lfingers4.setSliderPosition(90)
        self.lfingers4.setOrientation(QtCore.Qt.Vertical)
        self.lfingers4.setObjectName(_fromUtf8("lfingers4"))
        self.lfingers3 = QtGui.QSlider(self.Control)
        self.lfingers3.setGeometry(QtCore.QRect(773, 130, 29, 160))
        self.lfingers3.setMaximum(180)
        self.lfingers3.setSliderPosition(90)
        self.lfingers3.setOrientation(QtCore.Qt.Vertical)
        self.lfingers3.setObjectName(_fromUtf8("lfingers3"))
        self.lfingers2 = QtGui.QSlider(self.Control)
        self.lfingers2.setGeometry(QtCore.QRect(797, 113, 29, 160))
        self.lfingers2.setMaximum(180)
        self.lfingers2.setSliderPosition(90)
        self.lfingers2.setOrientation(QtCore.Qt.Vertical)
        self.lfingers2.setObjectName(_fromUtf8("lfingers2"))
        self.lfingers1 = QtGui.QSlider(self.Control)
        self.lfingers1.setGeometry(QtCore.QRect(824, 80, 29, 160))
        self.lfingers1.setMaximum(180)
        self.lfingers1.setSliderPosition(90)
        self.lfingers1.setOrientation(QtCore.Qt.Vertical)
        self.lfingers1.setObjectName(_fromUtf8("lfingers1"))
        self.udrotate = QtGui.QSlider(self.Control)
        self.udrotate.setEnabled(True)
        self.udrotate.setGeometry(QtCore.QRect(250, 40, 160, 29))
        self.udrotate.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.udrotate.setMaximum(180)
        self.udrotate.setProperty("value", 90)
        self.udrotate.setOrientation(QtCore.Qt.Horizontal)
        self.udrotate.setObjectName(_fromUtf8("udrotate"))
        self.label = QtGui.QLabel(self.Control)
        self.label.setGeometry(QtCore.QRect(140, 75, 71, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.labelrlrotate = QtGui.QLabel(self.Control)
        self.labelrlrotate.setGeometry(QtCore.QRect(220, 70, 31, 30))
        self.labelrlrotate.setObjectName(_fromUtf8("labelrlrotate"))
        self.labeludrotate = QtGui.QLabel(self.Control)
        self.labeludrotate.setGeometry(QtCore.QRect(220, 40, 31, 30))
        self.labeludrotate.setObjectName(_fromUtf8("labeludrotate"))
        self.label_19 = QtGui.QLabel(self.Control)
        self.label_19.setGeometry(QtCore.QRect(140, 40, 71, 30))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.rlrotate = QtGui.QSlider(self.Control)
        self.rlrotate.setGeometry(QtCore.QRect(250, 70, 160, 29))
        self.rlrotate.setMaximum(180)
        self.rlrotate.setProperty("value", 90)
        self.rlrotate.setOrientation(QtCore.Qt.Horizontal)
        self.rlrotate.setObjectName(_fromUtf8("rlrotate"))
        self.mouth = QtGui.QSlider(self.Control)
        self.mouth.setGeometry(QtCore.QRect(490, 80, 131, 29))
        self.mouth.setMaximum(70)
        self.mouth.setOrientation(QtCore.Qt.Horizontal)
        self.mouth.setObjectName(_fromUtf8("mouth"))
        self.horizontalSlider = QtGui.QSlider(self.Control)
        self.horizontalSlider.setGeometry(QtCore.QRect(400, 270, 91, 29))
        self.horizontalSlider.setMaximum(180)
        self.horizontalSlider.setSliderPosition(90)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.label_41 = QtGui.QLabel(self.Control)
        self.label_41.setGeometry(QtCore.QRect(506, 313, 16, 61))
        self.label_41.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_41.setFrameShadow(QtGui.QFrame.Plain)
        self.label_41.setMidLineWidth(0)
        self.label_41.setTextFormat(QtCore.Qt.PlainText)
        self.label_41.setScaledContents(False)
        self.label_41.setWordWrap(False)
        self.label_41.setMargin(0)
        self.label_41.setOpenExternalLinks(False)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.Control)
        self.label_42.setGeometry(QtCore.QRect(539, 290, 16, 81))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_44 = QtGui.QLabel(self.Control)
        self.label_44.setGeometry(QtCore.QRect(565, 264, 16, 81))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.Control)
        self.label_45.setGeometry(QtCore.QRect(590, 264, 21, 61))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_43 = QtGui.QLabel(self.Control)
        self.label_43.setGeometry(QtCore.QRect(684, 280, 21, 61))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_53 = QtGui.QLabel(self.Control)
        self.label_53.setGeometry(QtCore.QRect(540, 30, 67, 17))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.motionTime = QtGui.QLabel(self.Control)
        self.motionTime.setGeometry(QtCore.QRect(590, 30, 67, 17))
        self.motionTime.setObjectName(_fromUtf8("motionTime"))
        self.scriptName = QtGui.QLineEdit(self.Control)
        self.scriptName.setGeometry(QtCore.QRect(70, 0, 271, 27))
        self.scriptName.setObjectName(_fromUtf8("scriptName"))
        self.tabWidget.addTab(self.Control, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(3, 0, 390, 611))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_68 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_2.addWidget(self.label_68)
        self.nameMainScript = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.nameMainScript.setEnabled(True)
        self.nameMainScript.setText(_fromUtf8(""))
        self.nameMainScript.setObjectName(_fromUtf8("nameMainScript"))
        self.horizontalLayout_2.addWidget(self.nameMainScript)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.scriptNew = QtGui.QPushButton(self.verticalLayoutWidget)
        self.scriptNew.setObjectName(_fromUtf8("scriptNew"))
        self.horizontalLayout.addWidget(self.scriptNew)
        self.scriptRun = QtGui.QPushButton(self.verticalLayoutWidget)
        self.scriptRun.setObjectName(_fromUtf8("scriptRun"))
        self.horizontalLayout.addWidget(self.scriptRun)
        self.scriptSave = QtGui.QPushButton(self.verticalLayoutWidget)
        self.scriptSave.setObjectName(_fromUtf8("scriptSave"))
        self.horizontalLayout.addWidget(self.scriptSave)
        self.scriptOpen = QtGui.QPushButton(self.verticalLayoutWidget)
        self.scriptOpen.setObjectName(_fromUtf8("scriptOpen"))
        self.horizontalLayout.addWidget(self.scriptOpen)
        self.scriptClear = QtGui.QPushButton(self.verticalLayoutWidget)
        self.scriptClear.setObjectName(_fromUtf8("scriptClear"))
        self.horizontalLayout.addWidget(self.scriptClear)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget = QtGui.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout.addWidget(self.listWidget)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(398, 75, 140, 230))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.appendItem = QtGui.QPushButton(self.groupBox)
        self.appendItem.setGeometry(QtCore.QRect(15, 0, 110, 51))
        self.appendItem.setObjectName(_fromUtf8("appendItem"))
        self.delItemFromMain = QtGui.QPushButton(self.groupBox)
        self.delItemFromMain.setGeometry(QtCore.QRect(16, 60, 110, 51))
        self.delItemFromMain.setObjectName(_fromUtf8("delItemFromMain"))
        self.verticalLayout_3.addWidget(self.groupBox)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_56 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_3.addWidget(self.label_56, 1, 0, 1, 1)
        self.delayVal = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.delayVal.setFont(font)
        self.delayVal.setMinimum(1)
        self.delayVal.setMaximum(60)
        self.delayVal.setObjectName(_fromUtf8("delayVal"))
        self.gridLayout_3.addWidget(self.delayVal, 1, 1, 1, 1)
        self.addDelay = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.addDelay.setObjectName(_fromUtf8("addDelay"))
        self.gridLayout_3.addWidget(self.addDelay, 2, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.widget = QtGui.QWidget(self.tab_4)
        self.widget.setGeometry(QtCore.QRect(540, 0, 381, 610))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.runScriptFromList = QtGui.QPushButton(self.widget)
        self.runScriptFromList.setObjectName(_fromUtf8("runScriptFromList"))
        self.horizontalLayout_3.addWidget(self.runScriptFromList)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.delMotion = QtGui.QPushButton(self.widget)
        self.delMotion.setObjectName(_fromUtf8("delMotion"))
        self.horizontalLayout_3.addWidget(self.delMotion)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.motionList = QtGui.QListWidget(self.widget)
        self.motionList.setObjectName(_fromUtf8("motionList"))
        self.verticalLayout_2.addWidget(self.motionList)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 240, 881, 81))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.blueText = QtGui.QLineEdit(self.groupBox_9)
        self.blueText.setGeometry(QtCore.QRect(760, 20, 41, 27))
        self.blueText.setObjectName(_fromUtf8("blueText"))
        self.redText = QtGui.QLineEdit(self.groupBox_9)
        self.redText.setGeometry(QtCore.QRect(620, 21, 41, 27))
        self.redText.setObjectName(_fromUtf8("redText"))
        self.label_46 = QtGui.QLabel(self.groupBox_9)
        self.label_46.setGeometry(QtCore.QRect(740, 25, 16, 17))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.greenSlider = QtGui.QSlider(self.groupBox_9)
        self.greenSlider.setGeometry(QtCore.QRect(237, 21, 160, 29))
        self.greenSlider.setMaximum(255)
        self.greenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.greenSlider.setObjectName(_fromUtf8("greenSlider"))
        self.blueSlider = QtGui.QSlider(self.groupBox_9)
        self.blueSlider.setGeometry(QtCore.QRect(430, 21, 160, 29))
        self.blueSlider.setMaximum(255)
        self.blueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueSlider.setObjectName(_fromUtf8("blueSlider"))
        self.label_40 = QtGui.QLabel(self.groupBox_9)
        self.label_40.setGeometry(QtCore.QRect(670, 25, 16, 17))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_39 = QtGui.QLabel(self.groupBox_9)
        self.label_39.setGeometry(QtCore.QRect(600, 26, 16, 17))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.redSlider = QtGui.QSlider(self.groupBox_9)
        self.redSlider.setGeometry(QtCore.QRect(40, 21, 160, 29))
        self.redSlider.setMaximum(255)
        self.redSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redSlider.setObjectName(_fromUtf8("redSlider"))
        self.greenText = QtGui.QLineEdit(self.groupBox_9)
        self.greenText.setGeometry(QtCore.QRect(690, 20, 41, 27))
        self.greenText.setObjectName(_fromUtf8("greenText"))
        self.label_48 = QtGui.QLabel(self.groupBox_9)
        self.label_48.setGeometry(QtCore.QRect(214, 26, 16, 17))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.label_49 = QtGui.QLabel(self.groupBox_9)
        self.label_49.setGeometry(QtCore.QRect(410, 27, 16, 17))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.rgbOK = QtGui.QPushButton(self.groupBox_9)
        self.rgbOK.setGeometry(QtCore.QRect(820, 20, 51, 27))
        self.rgbOK.setObjectName(_fromUtf8("rgbOK"))
        self.label_50 = QtGui.QLabel(self.groupBox_9)
        self.label_50.setGeometry(QtCore.QRect(20, 26, 16, 17))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_7.setGeometry(QtCore.QRect(480, 50, 97, 22))
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_3.setGeometry(QtCore.QRect(550, 50, 97, 22))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.colorLed = QtGui.QGroupBox(self.groupBox_9)
        self.colorLed.setGeometry(QtCore.QRect(24, 50, 451, 21))
        self.colorLed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.colorLed.setTitle(_fromUtf8(""))
        self.colorLed.setFlat(False)
        self.colorLed.setCheckable(False)
        self.colorLed.setChecked(False)
        self.colorLed.setObjectName(_fromUtf8("colorLed"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 10, 901, 111))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.lineSay = QtGui.QLineEdit(self.groupBox_10)
        self.lineSay.setGeometry(QtCore.QRect(10, 30, 761, 27))
        self.lineSay.setObjectName(_fromUtf8("lineSay"))
        self.say = QtGui.QPushButton(self.groupBox_10)
        self.say.setGeometry(QtCore.QRect(790, 30, 99, 27))
        self.say.setObjectName(_fromUtf8("say"))
        self.label_135 = QtGui.QLabel(self.groupBox_10)
        self.label_135.setGeometry(QtCore.QRect(14, 63, 71, 21))
        self.label_135.setObjectName(_fromUtf8("label_135"))
        self.sayLang = QtGui.QComboBox(self.groupBox_10)
        self.sayLang.setGeometry(QtCore.QRect(90, 60, 111, 27))
        self.sayLang.setObjectName(_fromUtf8("sayLang"))
        self.sayLang.addItem(_fromUtf8(""))
        self.sayLang.addItem(_fromUtf8(""))
        self.label_136 = QtGui.QLabel(self.groupBox_10)
        self.label_136.setGeometry(QtCore.QRect(212, 63, 41, 21))
        self.label_136.setObjectName(_fromUtf8("label_136"))
        self.sayVoice = QtGui.QComboBox(self.groupBox_10)
        self.sayVoice.setGeometry(QtCore.QRect(262, 60, 111, 27))
        self.sayVoice.setObjectName(_fromUtf8("sayVoice"))
        self.sayVoice.addItem(_fromUtf8(""))
        self.sayVoice.addItem(_fromUtf8(""))
        self.sayVoice.addItem(_fromUtf8(""))
        self.sayVoice.addItem(_fromUtf8(""))
        self.sayEmotion = QtGui.QComboBox(self.groupBox_10)
        self.sayEmotion.setGeometry(QtCore.QRect(442, 60, 91, 27))
        self.sayEmotion.setObjectName(_fromUtf8("sayEmotion"))
        self.sayEmotion.addItem(_fromUtf8(""))
        self.sayEmotion.addItem(_fromUtf8(""))
        self.sayEmotion.addItem(_fromUtf8(""))
        self.sayEmotion.addItem(_fromUtf8(""))
        self.label_137 = QtGui.QLabel(self.groupBox_10)
        self.label_137.setGeometry(QtCore.QRect(380, 63, 61, 21))
        self.label_137.setObjectName(_fromUtf8("label_137"))
        self.sayOption = QtGui.QComboBox(self.groupBox_10)
        self.sayOption.setGeometry(QtCore.QRect(595, 60, 91, 27))
        self.sayOption.setObjectName(_fromUtf8("sayOption"))
        self.sayOption.addItem(_fromUtf8(""))
        self.sayOption.addItem(_fromUtf8(""))
        self.label_138 = QtGui.QLabel(self.groupBox_10)
        self.label_138.setGeometry(QtCore.QRect(542, 63, 61, 21))
        self.label_138.setObjectName(_fromUtf8("label_138"))
        self.saySpeed = QtGui.QComboBox(self.groupBox_10)
        self.saySpeed.setGeometry(QtCore.QRect(760, 60, 51, 27))
        self.saySpeed.setObjectName(_fromUtf8("saySpeed"))
        self.saySpeed.addItem(_fromUtf8(""))
        self.saySpeed.addItem(_fromUtf8(""))
        self.saySpeed.addItem(_fromUtf8(""))
        self.saySpeed.addItem(_fromUtf8(""))
        self.saySpeed.addItem(_fromUtf8(""))
        self.label_139 = QtGui.QLabel(self.groupBox_10)
        self.label_139.setGeometry(QtCore.QRect(700, 63, 61, 21))
        self.label_139.setObjectName(_fromUtf8("label_139"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 120, 901, 101))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.singPath = QtGui.QLineEdit(self.groupBox_11)
        self.singPath.setGeometry(QtCore.QRect(80, 30, 601, 27))
        self.singPath.setObjectName(_fromUtf8("singPath"))
        self.singPlay = QtGui.QPushButton(self.groupBox_11)
        self.singPlay.setGeometry(QtCore.QRect(808, 30, 81, 27))
        self.singPlay.setObjectName(_fromUtf8("singPlay"))
        self.singVolum = QtGui.QSlider(self.groupBox_11)
        self.singVolum.setGeometry(QtCore.QRect(60, 60, 160, 29))
        self.singVolum.setMaximum(100)
        self.singVolum.setProperty("value", 50)
        self.singVolum.setOrientation(QtCore.Qt.Horizontal)
        self.singVolum.setObjectName(_fromUtf8("singVolum"))
        self.label_54 = QtGui.QLabel(self.groupBox_11)
        self.label_54.setGeometry(QtCore.QRect(5, 65, 67, 17))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.volume = QtGui.QLabel(self.groupBox_11)
        self.volume.setGeometry(QtCore.QRect(230, 65, 51, 17))
        self.volume.setObjectName(_fromUtf8("volume"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_11)
        self.checkBox.setGeometry(QtCore.QRect(550, 60, 121, 22))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.singSpeedText = QtGui.QLabel(self.groupBox_11)
        self.singSpeedText.setGeometry(QtCore.QRect(500, 65, 51, 17))
        self.singSpeedText.setObjectName(_fromUtf8("singSpeedText"))
        self.label_70 = QtGui.QLabel(self.groupBox_11)
        self.label_70.setGeometry(QtCore.QRect(320, 65, 67, 17))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.singSpeed = QtGui.QSlider(self.groupBox_11)
        self.singSpeed.setGeometry(QtCore.QRect(375, 60, 111, 29))
        self.singSpeed.setMinimum(1)
        self.singSpeed.setMaximum(10)
        self.singSpeed.setProperty("value", 1)
        self.singSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.singSpeed.setObjectName(_fromUtf8("singSpeed"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_11)
        self.checkBox_2.setGeometry(QtCore.QRect(690, 60, 97, 22))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.singOpen = QtGui.QPushButton(self.groupBox_11)
        self.singOpen.setGeometry(QtCore.QRect(700, 30, 91, 27))
        self.singOpen.setObjectName(_fromUtf8("singOpen"))
        self.label_55 = QtGui.QLabel(self.groupBox_11)
        self.label_55.setGeometry(QtCore.QRect(6, 35, 67, 17))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 921, 581))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.lineRightPort = QtGui.QLineEdit(self.tab)
        self.lineRightPort.setGeometry(QtCore.QRect(537, 70, 251, 27))
        self.lineRightPort.setObjectName(_fromUtf8("lineRightPort"))
        self.lineHeadPort = QtGui.QLineEdit(self.tab)
        self.lineHeadPort.setGeometry(QtCore.QRect(537, 11, 251, 27))
        self.lineHeadPort.setObjectName(_fromUtf8("lineHeadPort"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(460, 45, 80, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(460, 74, 81, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineLeftPort = QtGui.QLineEdit(self.tab)
        self.lineLeftPort.setGeometry(QtCore.QRect(537, 40, 251, 27))
        self.lineLeftPort.setObjectName(_fromUtf8("lineLeftPort"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(460, 15, 81, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.widget1 = QtGui.QWidget(self.tab)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 236, 126))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.widget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.ipConnect = QtGui.QLineEdit(self.widget1)
        self.ipConnect.setObjectName(_fromUtf8("ipConnect"))
        self.horizontalLayout_4.addWidget(self.ipConnect)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_47 = QtGui.QLabel(self.widget1)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_5.addWidget(self.label_47)
        self.ipConnect_2 = QtGui.QLineEdit(self.widget1)
        self.ipConnect_2.setObjectName(_fromUtf8("ipConnect_2"))
        self.horizontalLayout_5.addWidget(self.ipConnect_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.buttonConnect = QtGui.QPushButton(self.widget1)
        self.buttonConnect.setObjectName(_fromUtf8("buttonConnect"))
        self.gridLayout_6.addWidget(self.buttonConnect, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 1, 1, 1)
        self.buttonDisconnect = QtGui.QPushButton(self.widget1)
        self.buttonDisconnect.setObjectName(_fromUtf8("buttonDisconnect"))
        self.gridLayout_6.addWidget(self.buttonDisconnect, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_20 = QtGui.QLabel(self.widget1)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_7.addWidget(self.label_20)
        self.connection1 = QtGui.QLabel(self.widget1)
        self.connection1.setObjectName(_fromUtf8("connection1"))
        self.horizontalLayout_7.addWidget(self.connection1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 301, 341))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(21, 147, 61, 30))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(19, 117, 61, 30))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(20, 87, 61, 30))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(21, 57, 61, 30))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 28, 81, 30))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.minOmoplateR = QtGui.QLineEdit(self.groupBox_3)
        self.minOmoplateR.setGeometry(QtCore.QRect(100, 30, 41, 27))
        self.minOmoplateR.setText(_fromUtf8(""))
        self.minOmoplateR.setObjectName(_fromUtf8("minOmoplateR"))
        self.maxOmoplateR = QtGui.QLineEdit(self.groupBox_3)
        self.maxOmoplateR.setGeometry(QtCore.QRect(150, 30, 41, 27))
        self.maxOmoplateR.setText(_fromUtf8(""))
        self.maxOmoplateR.setObjectName(_fromUtf8("maxOmoplateR"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(105, 9, 31, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(155, 9, 31, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.minShoulderR = QtGui.QLineEdit(self.groupBox_3)
        self.minShoulderR.setGeometry(QtCore.QRect(100, 60, 41, 27))
        self.minShoulderR.setText(_fromUtf8(""))
        self.minShoulderR.setObjectName(_fromUtf8("minShoulderR"))
        self.maxShoulderR = QtGui.QLineEdit(self.groupBox_3)
        self.maxShoulderR.setGeometry(QtCore.QRect(150, 60, 41, 27))
        self.maxShoulderR.setText(_fromUtf8(""))
        self.maxShoulderR.setObjectName(_fromUtf8("maxShoulderR"))
        self.minRotateR = QtGui.QLineEdit(self.groupBox_3)
        self.minRotateR.setGeometry(QtCore.QRect(100, 90, 41, 27))
        self.minRotateR.setText(_fromUtf8(""))
        self.minRotateR.setObjectName(_fromUtf8("minRotateR"))
        self.maxRotateR = QtGui.QLineEdit(self.groupBox_3)
        self.maxRotateR.setGeometry(QtCore.QRect(150, 90, 41, 27))
        self.maxRotateR.setText(_fromUtf8(""))
        self.maxRotateR.setObjectName(_fromUtf8("maxRotateR"))
        self.minBicepsR = QtGui.QLineEdit(self.groupBox_3)
        self.minBicepsR.setGeometry(QtCore.QRect(100, 120, 41, 27))
        self.minBicepsR.setText(_fromUtf8(""))
        self.minBicepsR.setObjectName(_fromUtf8("minBicepsR"))
        self.maxBicepsR = QtGui.QLineEdit(self.groupBox_3)
        self.maxBicepsR.setGeometry(QtCore.QRect(150, 120, 41, 27))
        self.maxBicepsR.setText(_fromUtf8(""))
        self.maxBicepsR.setObjectName(_fromUtf8("maxBicepsR"))
        self.minPalmR = QtGui.QLineEdit(self.groupBox_3)
        self.minPalmR.setGeometry(QtCore.QRect(100, 150, 41, 27))
        self.minPalmR.setText(_fromUtf8(""))
        self.minPalmR.setObjectName(_fromUtf8("minPalmR"))
        self.maxPalmR = QtGui.QLineEdit(self.groupBox_3)
        self.maxPalmR.setGeometry(QtCore.QRect(150, 150, 41, 27))
        self.maxPalmR.setText(_fromUtf8(""))
        self.maxPalmR.setObjectName(_fromUtf8("maxPalmR"))
        self.minFinger3R = QtGui.QLineEdit(self.groupBox_3)
        self.minFinger3R.setGeometry(QtCore.QRect(100, 253, 41, 27))
        self.minFinger3R.setText(_fromUtf8(""))
        self.minFinger3R.setObjectName(_fromUtf8("minFinger3R"))
        self.minFinger1R = QtGui.QLineEdit(self.groupBox_3)
        self.minFinger1R.setGeometry(QtCore.QRect(100, 193, 41, 27))
        self.minFinger1R.setText(_fromUtf8(""))
        self.minFinger1R.setObjectName(_fromUtf8("minFinger1R"))
        self.maxFinger5R = QtGui.QLineEdit(self.groupBox_3)
        self.maxFinger5R.setGeometry(QtCore.QRect(149, 313, 41, 27))
        self.maxFinger5R.setText(_fromUtf8(""))
        self.maxFinger5R.setObjectName(_fromUtf8("maxFinger5R"))
        self.maxFinger4R = QtGui.QLineEdit(self.groupBox_3)
        self.maxFinger4R.setGeometry(QtCore.QRect(149, 283, 41, 27))
        self.maxFinger4R.setText(_fromUtf8(""))
        self.maxFinger4R.setObjectName(_fromUtf8("maxFinger4R"))
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(18, 280, 61, 30))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.maxFinger2R = QtGui.QLineEdit(self.groupBox_3)
        self.maxFinger2R.setGeometry(QtCore.QRect(150, 223, 41, 27))
        self.maxFinger2R.setText(_fromUtf8(""))
        self.maxFinger2R.setObjectName(_fromUtf8("maxFinger2R"))
        self.maxFinger1R = QtGui.QLineEdit(self.groupBox_3)
        self.maxFinger1R.setGeometry(QtCore.QRect(149, 193, 41, 27))
        self.maxFinger1R.setText(_fromUtf8(""))
        self.maxFinger1R.setObjectName(_fromUtf8("maxFinger1R"))
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(20, 310, 61, 30))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.maxFinger3R = QtGui.QLineEdit(self.groupBox_3)
        self.maxFinger3R.setGeometry(QtCore.QRect(149, 253, 41, 27))
        self.maxFinger3R.setText(_fromUtf8(""))
        self.maxFinger3R.setObjectName(_fromUtf8("maxFinger3R"))
        self.minFinger5R = QtGui.QLineEdit(self.groupBox_3)
        self.minFinger5R.setGeometry(QtCore.QRect(100, 313, 41, 27))
        self.minFinger5R.setText(_fromUtf8(""))
        self.minFinger5R.setObjectName(_fromUtf8("minFinger5R"))
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(19, 250, 61, 30))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.minFinger4R = QtGui.QLineEdit(self.groupBox_3)
        self.minFinger4R.setGeometry(QtCore.QRect(100, 283, 41, 27))
        self.minFinger4R.setText(_fromUtf8(""))
        self.minFinger4R.setObjectName(_fromUtf8("minFinger4R"))
        self.minFinger2R = QtGui.QLineEdit(self.groupBox_3)
        self.minFinger2R.setGeometry(QtCore.QRect(100, 223, 41, 27))
        self.minFinger2R.setText(_fromUtf8(""))
        self.minFinger2R.setObjectName(_fromUtf8("minFinger2R"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(19, 191, 81, 30))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(20, 220, 61, 30))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.strFinger2R = QtGui.QLineEdit(self.groupBox_3)
        self.strFinger2R.setGeometry(QtCore.QRect(200, 223, 41, 27))
        self.strFinger2R.setText(_fromUtf8(""))
        self.strFinger2R.setObjectName(_fromUtf8("strFinger2R"))
        self.strPalmR = QtGui.QLineEdit(self.groupBox_3)
        self.strPalmR.setGeometry(QtCore.QRect(201, 150, 41, 27))
        self.strPalmR.setText(_fromUtf8(""))
        self.strPalmR.setObjectName(_fromUtf8("strPalmR"))
        self.strBicepsR = QtGui.QLineEdit(self.groupBox_3)
        self.strBicepsR.setGeometry(QtCore.QRect(201, 120, 41, 27))
        self.strBicepsR.setText(_fromUtf8(""))
        self.strBicepsR.setObjectName(_fromUtf8("strBicepsR"))
        self.label_38 = QtGui.QLabel(self.groupBox_3)
        self.label_38.setGeometry(QtCore.QRect(209, 9, 31, 17))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.strShoulderR = QtGui.QLineEdit(self.groupBox_3)
        self.strShoulderR.setGeometry(QtCore.QRect(200, 60, 41, 27))
        self.strShoulderR.setText(_fromUtf8(""))
        self.strShoulderR.setObjectName(_fromUtf8("strShoulderR"))
        self.strOmoplateR = QtGui.QLineEdit(self.groupBox_3)
        self.strOmoplateR.setGeometry(QtCore.QRect(201, 30, 41, 27))
        self.strOmoplateR.setText(_fromUtf8(""))
        self.strOmoplateR.setObjectName(_fromUtf8("strOmoplateR"))
        self.strRotateR = QtGui.QLineEdit(self.groupBox_3)
        self.strRotateR.setGeometry(QtCore.QRect(201, 90, 41, 27))
        self.strRotateR.setText(_fromUtf8(""))
        self.strRotateR.setObjectName(_fromUtf8("strRotateR"))
        self.strFinger5R = QtGui.QLineEdit(self.groupBox_3)
        self.strFinger5R.setGeometry(QtCore.QRect(200, 313, 41, 27))
        self.strFinger5R.setText(_fromUtf8(""))
        self.strFinger5R.setObjectName(_fromUtf8("strFinger5R"))
        self.strFinger1R = QtGui.QLineEdit(self.groupBox_3)
        self.strFinger1R.setGeometry(QtCore.QRect(200, 193, 41, 27))
        self.strFinger1R.setText(_fromUtf8(""))
        self.strFinger1R.setObjectName(_fromUtf8("strFinger1R"))
        self.strFinger4R = QtGui.QLineEdit(self.groupBox_3)
        self.strFinger4R.setGeometry(QtCore.QRect(200, 283, 41, 27))
        self.strFinger4R.setText(_fromUtf8(""))
        self.strFinger4R.setObjectName(_fromUtf8("strFinger4R"))
        self.strFinger3R = QtGui.QLineEdit(self.groupBox_3)
        self.strFinger3R.setGeometry(QtCore.QRect(200, 253, 41, 27))
        self.strFinger3R.setText(_fromUtf8(""))
        self.strFinger3R.setObjectName(_fromUtf8("strFinger3R"))
        self.pinPalmR = QtGui.QLineEdit(self.groupBox_3)
        self.pinPalmR.setGeometry(QtCore.QRect(250, 150, 41, 27))
        self.pinPalmR.setText(_fromUtf8(""))
        self.pinPalmR.setObjectName(_fromUtf8("pinPalmR"))
        self.pinBicepsR = QtGui.QLineEdit(self.groupBox_3)
        self.pinBicepsR.setGeometry(QtCore.QRect(250, 120, 41, 27))
        self.pinBicepsR.setText(_fromUtf8(""))
        self.pinBicepsR.setObjectName(_fromUtf8("pinBicepsR"))
        self.label_59 = QtGui.QLabel(self.groupBox_3)
        self.label_59.setGeometry(QtCore.QRect(258, 9, 31, 17))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.pinFinger5R = QtGui.QLineEdit(self.groupBox_3)
        self.pinFinger5R.setGeometry(QtCore.QRect(249, 313, 41, 27))
        self.pinFinger5R.setText(_fromUtf8(""))
        self.pinFinger5R.setObjectName(_fromUtf8("pinFinger5R"))
        self.pinFinger1R = QtGui.QLineEdit(self.groupBox_3)
        self.pinFinger1R.setGeometry(QtCore.QRect(249, 193, 41, 27))
        self.pinFinger1R.setText(_fromUtf8(""))
        self.pinFinger1R.setObjectName(_fromUtf8("pinFinger1R"))
        self.pinRotateR = QtGui.QLineEdit(self.groupBox_3)
        self.pinRotateR.setGeometry(QtCore.QRect(250, 90, 41, 27))
        self.pinRotateR.setText(_fromUtf8(""))
        self.pinRotateR.setObjectName(_fromUtf8("pinRotateR"))
        self.pinShoulderPinR = QtGui.QLineEdit(self.groupBox_3)
        self.pinShoulderPinR.setGeometry(QtCore.QRect(250, 60, 41, 27))
        self.pinShoulderPinR.setText(_fromUtf8(""))
        self.pinShoulderPinR.setObjectName(_fromUtf8("pinShoulderPinR"))
        self.pinFinger3R = QtGui.QLineEdit(self.groupBox_3)
        self.pinFinger3R.setGeometry(QtCore.QRect(249, 253, 41, 27))
        self.pinFinger3R.setText(_fromUtf8(""))
        self.pinFinger3R.setObjectName(_fromUtf8("pinFinger3R"))
        self.pinFinger4R = QtGui.QLineEdit(self.groupBox_3)
        self.pinFinger4R.setGeometry(QtCore.QRect(249, 283, 41, 27))
        self.pinFinger4R.setText(_fromUtf8(""))
        self.pinFinger4R.setObjectName(_fromUtf8("pinFinger4R"))
        self.pinOmoplateR = QtGui.QLineEdit(self.groupBox_3)
        self.pinOmoplateR.setGeometry(QtCore.QRect(250, 30, 41, 27))
        self.pinOmoplateR.setText(_fromUtf8(""))
        self.pinOmoplateR.setObjectName(_fromUtf8("pinOmoplateR"))
        self.pinFinger2R = QtGui.QLineEdit(self.groupBox_3)
        self.pinFinger2R.setGeometry(QtCore.QRect(249, 223, 41, 27))
        self.pinFinger2R.setText(_fromUtf8(""))
        self.pinFinger2R.setObjectName(_fromUtf8("pinFinger2R"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_4.setGeometry(QtCore.QRect(330, 0, 301, 361))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_26 = QtGui.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(21, 147, 61, 30))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(19, 117, 61, 30))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(20, 87, 61, 30))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(21, 57, 61, 30))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(20, 28, 81, 30))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.minOmoplateL = QtGui.QLineEdit(self.groupBox_4)
        self.minOmoplateL.setGeometry(QtCore.QRect(100, 30, 41, 27))
        self.minOmoplateL.setText(_fromUtf8(""))
        self.minOmoplateL.setObjectName(_fromUtf8("minOmoplateL"))
        self.maxOmoplateL = QtGui.QLineEdit(self.groupBox_4)
        self.maxOmoplateL.setGeometry(QtCore.QRect(150, 30, 41, 27))
        self.maxOmoplateL.setText(_fromUtf8(""))
        self.maxOmoplateL.setObjectName(_fromUtf8("maxOmoplateL"))
        self.label_30 = QtGui.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(105, 9, 31, 17))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(155, 9, 31, 17))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.minShoulderL = QtGui.QLineEdit(self.groupBox_4)
        self.minShoulderL.setGeometry(QtCore.QRect(100, 60, 41, 27))
        self.minShoulderL.setText(_fromUtf8(""))
        self.minShoulderL.setObjectName(_fromUtf8("minShoulderL"))
        self.maxShoulderL = QtGui.QLineEdit(self.groupBox_4)
        self.maxShoulderL.setGeometry(QtCore.QRect(150, 60, 41, 27))
        self.maxShoulderL.setText(_fromUtf8(""))
        self.maxShoulderL.setObjectName(_fromUtf8("maxShoulderL"))
        self.minRotateL = QtGui.QLineEdit(self.groupBox_4)
        self.minRotateL.setGeometry(QtCore.QRect(100, 90, 41, 27))
        self.minRotateL.setText(_fromUtf8(""))
        self.minRotateL.setObjectName(_fromUtf8("minRotateL"))
        self.maxRotateL = QtGui.QLineEdit(self.groupBox_4)
        self.maxRotateL.setGeometry(QtCore.QRect(150, 90, 41, 27))
        self.maxRotateL.setText(_fromUtf8(""))
        self.maxRotateL.setObjectName(_fromUtf8("maxRotateL"))
        self.minBicepsL = QtGui.QLineEdit(self.groupBox_4)
        self.minBicepsL.setGeometry(QtCore.QRect(100, 120, 41, 27))
        self.minBicepsL.setText(_fromUtf8(""))
        self.minBicepsL.setObjectName(_fromUtf8("minBicepsL"))
        self.maxBicepsL = QtGui.QLineEdit(self.groupBox_4)
        self.maxBicepsL.setGeometry(QtCore.QRect(150, 120, 41, 27))
        self.maxBicepsL.setText(_fromUtf8(""))
        self.maxBicepsL.setObjectName(_fromUtf8("maxBicepsL"))
        self.minPalmL = QtGui.QLineEdit(self.groupBox_4)
        self.minPalmL.setGeometry(QtCore.QRect(100, 150, 41, 27))
        self.minPalmL.setText(_fromUtf8(""))
        self.minPalmL.setObjectName(_fromUtf8("minPalmL"))
        self.maxPalmL = QtGui.QLineEdit(self.groupBox_4)
        self.maxPalmL.setGeometry(QtCore.QRect(150, 150, 41, 27))
        self.maxPalmL.setText(_fromUtf8(""))
        self.maxPalmL.setObjectName(_fromUtf8("maxPalmL"))
        self.minFinger3L = QtGui.QLineEdit(self.groupBox_4)
        self.minFinger3L.setGeometry(QtCore.QRect(99, 253, 41, 27))
        self.minFinger3L.setText(_fromUtf8(""))
        self.minFinger3L.setObjectName(_fromUtf8("minFinger3L"))
        self.minFinger1L = QtGui.QLineEdit(self.groupBox_4)
        self.minFinger1L.setGeometry(QtCore.QRect(99, 193, 41, 27))
        self.minFinger1L.setText(_fromUtf8(""))
        self.minFinger1L.setObjectName(_fromUtf8("minFinger1L"))
        self.maxFinger5L = QtGui.QLineEdit(self.groupBox_4)
        self.maxFinger5L.setGeometry(QtCore.QRect(149, 313, 41, 27))
        self.maxFinger5L.setText(_fromUtf8(""))
        self.maxFinger5L.setObjectName(_fromUtf8("maxFinger5L"))
        self.maxFinger4L = QtGui.QLineEdit(self.groupBox_4)
        self.maxFinger4L.setGeometry(QtCore.QRect(149, 283, 41, 27))
        self.maxFinger4L.setText(_fromUtf8(""))
        self.maxFinger4L.setObjectName(_fromUtf8("maxFinger4L"))
        self.label_32 = QtGui.QLabel(self.groupBox_4)
        self.label_32.setGeometry(QtCore.QRect(18, 280, 61, 30))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.maxFinger2L = QtGui.QLineEdit(self.groupBox_4)
        self.maxFinger2L.setGeometry(QtCore.QRect(149, 223, 41, 27))
        self.maxFinger2L.setText(_fromUtf8(""))
        self.maxFinger2L.setObjectName(_fromUtf8("maxFinger2L"))
        self.maxFinger1L = QtGui.QLineEdit(self.groupBox_4)
        self.maxFinger1L.setGeometry(QtCore.QRect(149, 193, 41, 27))
        self.maxFinger1L.setText(_fromUtf8(""))
        self.maxFinger1L.setObjectName(_fromUtf8("maxFinger1L"))
        self.label_33 = QtGui.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(20, 310, 61, 30))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.maxFinger3L = QtGui.QLineEdit(self.groupBox_4)
        self.maxFinger3L.setGeometry(QtCore.QRect(149, 253, 41, 27))
        self.maxFinger3L.setText(_fromUtf8(""))
        self.maxFinger3L.setObjectName(_fromUtf8("maxFinger3L"))
        self.minFinger5L = QtGui.QLineEdit(self.groupBox_4)
        self.minFinger5L.setGeometry(QtCore.QRect(99, 313, 41, 27))
        self.minFinger5L.setText(_fromUtf8(""))
        self.minFinger5L.setObjectName(_fromUtf8("minFinger5L"))
        self.label_34 = QtGui.QLabel(self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(19, 250, 61, 30))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.minFinger4L = QtGui.QLineEdit(self.groupBox_4)
        self.minFinger4L.setGeometry(QtCore.QRect(99, 283, 41, 27))
        self.minFinger4L.setText(_fromUtf8(""))
        self.minFinger4L.setObjectName(_fromUtf8("minFinger4L"))
        self.minFinger2L = QtGui.QLineEdit(self.groupBox_4)
        self.minFinger2L.setGeometry(QtCore.QRect(99, 223, 41, 27))
        self.minFinger2L.setText(_fromUtf8(""))
        self.minFinger2L.setObjectName(_fromUtf8("minFinger2L"))
        self.label_35 = QtGui.QLabel(self.groupBox_4)
        self.label_35.setGeometry(QtCore.QRect(19, 191, 81, 30))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_37 = QtGui.QLabel(self.groupBox_4)
        self.label_37.setGeometry(QtCore.QRect(20, 220, 61, 30))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.strFinger2L = QtGui.QLineEdit(self.groupBox_4)
        self.strFinger2L.setGeometry(QtCore.QRect(200, 223, 41, 27))
        self.strFinger2L.setText(_fromUtf8(""))
        self.strFinger2L.setObjectName(_fromUtf8("strFinger2L"))
        self.strPalmL = QtGui.QLineEdit(self.groupBox_4)
        self.strPalmL.setGeometry(QtCore.QRect(201, 150, 41, 27))
        self.strPalmL.setText(_fromUtf8(""))
        self.strPalmL.setObjectName(_fromUtf8("strPalmL"))
        self.strBicepsL = QtGui.QLineEdit(self.groupBox_4)
        self.strBicepsL.setGeometry(QtCore.QRect(201, 120, 41, 27))
        self.strBicepsL.setText(_fromUtf8(""))
        self.strBicepsL.setObjectName(_fromUtf8("strBicepsL"))
        self.label_57 = QtGui.QLabel(self.groupBox_4)
        self.label_57.setGeometry(QtCore.QRect(209, 9, 31, 17))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.strShoulderL = QtGui.QLineEdit(self.groupBox_4)
        self.strShoulderL.setGeometry(QtCore.QRect(201, 60, 41, 27))
        self.strShoulderL.setText(_fromUtf8(""))
        self.strShoulderL.setObjectName(_fromUtf8("strShoulderL"))
        self.strOmoplateL = QtGui.QLineEdit(self.groupBox_4)
        self.strOmoplateL.setGeometry(QtCore.QRect(201, 30, 41, 27))
        self.strOmoplateL.setText(_fromUtf8(""))
        self.strOmoplateL.setObjectName(_fromUtf8("strOmoplateL"))
        self.strRotateL = QtGui.QLineEdit(self.groupBox_4)
        self.strRotateL.setGeometry(QtCore.QRect(201, 90, 41, 27))
        self.strRotateL.setText(_fromUtf8(""))
        self.strRotateL.setObjectName(_fromUtf8("strRotateL"))
        self.strFinger5L = QtGui.QLineEdit(self.groupBox_4)
        self.strFinger5L.setGeometry(QtCore.QRect(200, 313, 41, 27))
        self.strFinger5L.setText(_fromUtf8(""))
        self.strFinger5L.setObjectName(_fromUtf8("strFinger5L"))
        self.strFinger1L = QtGui.QLineEdit(self.groupBox_4)
        self.strFinger1L.setGeometry(QtCore.QRect(200, 193, 41, 27))
        self.strFinger1L.setText(_fromUtf8(""))
        self.strFinger1L.setObjectName(_fromUtf8("strFinger1L"))
        self.strFinger4L = QtGui.QLineEdit(self.groupBox_4)
        self.strFinger4L.setGeometry(QtCore.QRect(200, 283, 41, 27))
        self.strFinger4L.setText(_fromUtf8(""))
        self.strFinger4L.setObjectName(_fromUtf8("strFinger4L"))
        self.strFinger3L = QtGui.QLineEdit(self.groupBox_4)
        self.strFinger3L.setGeometry(QtCore.QRect(200, 253, 41, 27))
        self.strFinger3L.setText(_fromUtf8(""))
        self.strFinger3L.setObjectName(_fromUtf8("strFinger3L"))
        self.pinPalmL = QtGui.QLineEdit(self.groupBox_4)
        self.pinPalmL.setGeometry(QtCore.QRect(250, 150, 41, 27))
        self.pinPalmL.setText(_fromUtf8(""))
        self.pinPalmL.setObjectName(_fromUtf8("pinPalmL"))
        self.pinBicepsL = QtGui.QLineEdit(self.groupBox_4)
        self.pinBicepsL.setGeometry(QtCore.QRect(250, 120, 41, 27))
        self.pinBicepsL.setText(_fromUtf8(""))
        self.pinBicepsL.setObjectName(_fromUtf8("pinBicepsL"))
        self.label_60 = QtGui.QLabel(self.groupBox_4)
        self.label_60.setGeometry(QtCore.QRect(258, 9, 31, 17))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.pinFinger5L = QtGui.QLineEdit(self.groupBox_4)
        self.pinFinger5L.setGeometry(QtCore.QRect(249, 313, 41, 27))
        self.pinFinger5L.setText(_fromUtf8(""))
        self.pinFinger5L.setObjectName(_fromUtf8("pinFinger5L"))
        self.pinFinger1L = QtGui.QLineEdit(self.groupBox_4)
        self.pinFinger1L.setGeometry(QtCore.QRect(249, 193, 41, 27))
        self.pinFinger1L.setText(_fromUtf8(""))
        self.pinFinger1L.setObjectName(_fromUtf8("pinFinger1L"))
        self.pinRotateL = QtGui.QLineEdit(self.groupBox_4)
        self.pinRotateL.setGeometry(QtCore.QRect(250, 90, 41, 27))
        self.pinRotateL.setText(_fromUtf8(""))
        self.pinRotateL.setObjectName(_fromUtf8("pinRotateL"))
        self.pinShoulderPinL = QtGui.QLineEdit(self.groupBox_4)
        self.pinShoulderPinL.setGeometry(QtCore.QRect(250, 60, 41, 27))
        self.pinShoulderPinL.setText(_fromUtf8(""))
        self.pinShoulderPinL.setObjectName(_fromUtf8("pinShoulderPinL"))
        self.pinFinger3L = QtGui.QLineEdit(self.groupBox_4)
        self.pinFinger3L.setGeometry(QtCore.QRect(249, 253, 41, 27))
        self.pinFinger3L.setText(_fromUtf8(""))
        self.pinFinger3L.setObjectName(_fromUtf8("pinFinger3L"))
        self.pinFinger4L = QtGui.QLineEdit(self.groupBox_4)
        self.pinFinger4L.setGeometry(QtCore.QRect(249, 283, 41, 27))
        self.pinFinger4L.setText(_fromUtf8(""))
        self.pinFinger4L.setObjectName(_fromUtf8("pinFinger4L"))
        self.pinOmoplateL = QtGui.QLineEdit(self.groupBox_4)
        self.pinOmoplateL.setGeometry(QtCore.QRect(250, 30, 41, 27))
        self.pinOmoplateL.setText(_fromUtf8(""))
        self.pinOmoplateL.setObjectName(_fromUtf8("pinOmoplateL"))
        self.pinFinger2L = QtGui.QLineEdit(self.groupBox_4)
        self.pinFinger2L.setGeometry(QtCore.QRect(249, 223, 41, 27))
        self.pinFinger2L.setText(_fromUtf8(""))
        self.pinFinger2L.setObjectName(_fromUtf8("pinFinger2L"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 350, 311, 181))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.maxMouth = QtGui.QLineEdit(self.groupBox_5)
        self.maxMouth.setGeometry(QtCore.QRect(150, 50, 41, 27))
        self.maxMouth.setObjectName(_fromUtf8("maxMouth"))
        self.label_61 = QtGui.QLabel(self.groupBox_5)
        self.label_61.setGeometry(QtCore.QRect(209, 29, 31, 17))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.strRLRotate = QtGui.QLineEdit(self.groupBox_5)
        self.strRLRotate.setGeometry(QtCore.QRect(201, 110, 41, 27))
        self.strRLRotate.setObjectName(_fromUtf8("strRLRotate"))
        self.pinUDRotate = QtGui.QLineEdit(self.groupBox_5)
        self.pinUDRotate.setGeometry(QtCore.QRect(250, 80, 41, 27))
        self.pinUDRotate.setObjectName(_fromUtf8("pinUDRotate"))
        self.label_62 = QtGui.QLabel(self.groupBox_5)
        self.label_62.setGeometry(QtCore.QRect(258, 29, 31, 17))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.maxUDRotate = QtGui.QLineEdit(self.groupBox_5)
        self.maxUDRotate.setGeometry(QtCore.QRect(150, 80, 41, 27))
        self.maxUDRotate.setObjectName(_fromUtf8("maxUDRotate"))
        self.label_63 = QtGui.QLabel(self.groupBox_5)
        self.label_63.setGeometry(QtCore.QRect(20, 48, 81, 30))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.pinRLRotate = QtGui.QLineEdit(self.groupBox_5)
        self.pinRLRotate.setGeometry(QtCore.QRect(250, 110, 41, 27))
        self.pinRLRotate.setObjectName(_fromUtf8("pinRLRotate"))
        self.label_64 = QtGui.QLabel(self.groupBox_5)
        self.label_64.setGeometry(QtCore.QRect(155, 29, 31, 17))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.minUDRotate = QtGui.QLineEdit(self.groupBox_5)
        self.minUDRotate.setGeometry(QtCore.QRect(100, 80, 41, 27))
        self.minUDRotate.setObjectName(_fromUtf8("minUDRotate"))
        self.pinMouth = QtGui.QLineEdit(self.groupBox_5)
        self.pinMouth.setGeometry(QtCore.QRect(250, 50, 41, 27))
        self.pinMouth.setObjectName(_fromUtf8("pinMouth"))
        self.strMouth = QtGui.QLineEdit(self.groupBox_5)
        self.strMouth.setGeometry(QtCore.QRect(201, 50, 41, 27))
        self.strMouth.setObjectName(_fromUtf8("strMouth"))
        self.label_65 = QtGui.QLabel(self.groupBox_5)
        self.label_65.setGeometry(QtCore.QRect(20, 77, 71, 30))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.label_66 = QtGui.QLabel(self.groupBox_5)
        self.label_66.setGeometry(QtCore.QRect(20, 107, 71, 30))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.label_67 = QtGui.QLabel(self.groupBox_5)
        self.label_67.setGeometry(QtCore.QRect(105, 29, 31, 17))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.minRLRotate = QtGui.QLineEdit(self.groupBox_5)
        self.minRLRotate.setGeometry(QtCore.QRect(100, 110, 41, 27))
        self.minRLRotate.setObjectName(_fromUtf8("minRLRotate"))
        self.strUDRotate = QtGui.QLineEdit(self.groupBox_5)
        self.strUDRotate.setGeometry(QtCore.QRect(201, 80, 41, 27))
        self.strUDRotate.setObjectName(_fromUtf8("strUDRotate"))
        self.minMouth = QtGui.QLineEdit(self.groupBox_5)
        self.minMouth.setGeometry(QtCore.QRect(100, 50, 41, 27))
        self.minMouth.setObjectName(_fromUtf8("minMouth"))
        self.maxRLRotate = QtGui.QLineEdit(self.groupBox_5)
        self.maxRLRotate.setGeometry(QtCore.QRect(150, 110, 41, 27))
        self.maxRLRotate.setObjectName(_fromUtf8("maxRLRotate"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.seveSettings = QtGui.QPushButton(self.tab_2)
        self.seveSettings.setGeometry(QtCore.QRect(820, 586, 99, 27))
        self.seveSettings.setObjectName(_fromUtf8("seveSettings"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        inmoovform.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(inmoovform)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 935, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu1 = QtGui.QMenu(self.menuBar)
        self.menu1.setObjectName(_fromUtf8("menu1"))
        self.menuScript = QtGui.QMenu(self.menuBar)
        self.menuScript.setObjectName(_fromUtf8("menuScript"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        inmoovform.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(inmoovform)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        inmoovform.setStatusBar(self.statusBar)
        self.action1 = QtGui.QAction(inmoovform)
        self.action1.setObjectName(_fromUtf8("action1"))
        self.actionExit = QtGui.QAction(inmoovform)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave_Sattings_As = QtGui.QAction(inmoovform)
        self.actionSave_Sattings_As.setObjectName(_fromUtf8("actionSave_Sattings_As"))
        self.actionOpen_Script = QtGui.QAction(inmoovform)
        self.actionOpen_Script.setObjectName(_fromUtf8("actionOpen_Script"))
        self.actionAbuot = QtGui.QAction(inmoovform)
        self.actionAbuot.setObjectName(_fromUtf8("actionAbuot"))
        self.actionSite = QtGui.QAction(inmoovform)
        self.actionSite.setObjectName(_fromUtf8("actionSite"))
        self.actionCheck_for_Update = QtGui.QAction(inmoovform)
        self.actionCheck_for_Update.setObjectName(_fromUtf8("actionCheck_for_Update"))
        self.actionSave = QtGui.QAction(inmoovform)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionReference = QtGui.QAction(inmoovform)
        self.actionReference.setObjectName(_fromUtf8("actionReference"))
        self.menu1.addAction(self.actionSave_Sattings_As)
        self.menu1.addAction(self.action1)
        self.menu1.addSeparator()
        self.menu1.addAction(self.actionExit)
        self.menuScript.addAction(self.actionOpen_Script)
        self.menuScript.addAction(self.actionSave)
        self.menuHelp.addAction(self.actionCheck_for_Update)
        self.menuHelp.addAction(self.actionAbuot)
        self.menuHelp.addAction(self.actionSite)
        self.menuHelp.addAction(self.actionReference)
        self.menuBar.addAction(self.menu1.menuAction())
        self.menuBar.addAction(self.menuScript.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(inmoovform)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(inmoovform)

    def retranslateUi(self, inmoovform):
        inmoovform.setWindowTitle(_translate("inmoovform", "inmoovform", None))
        self.labelmouth.setText(_translate("inmoovform", "0", None))
        self.label_36.setText(_translate("inmoovform", "Mouth", None))
        self.motionRec.setText(_translate("inmoovform", "Rec", None))
        self.motionPlay.setText(_translate("inmoovform", "Play", None))
        self.motionStop.setText(_translate("inmoovform", "Stop", None))
        self.label_58.setText(_translate("inmoovform", "Connection:", None))
        self.connection.setText(_translate("inmoovform", "lost", None))
        self.checkRightHand.setText(_translate("inmoovform", "Right Hand", None))
        self.checkLeftHand.setText(_translate("inmoovform", "Left Hand", None))
        self.checkHead.setText(_translate("inmoovform", "Head", None))
        self.label_51.setText(_translate("inmoovform", "Status:", None))
        self.statusMotion.setText(_translate("inmoovform", "Stop", None))
        self.label_52.setText(_translate("inmoovform", "Script:", None))
        self.labelromoplate.setText(_translate("inmoovform", "20", None))
        self.label_6.setText(_translate("inmoovform", "O\n"
"m\n"
"o", None))
        self.labelrshoulder.setText(_translate("inmoovform", "30", None))
        self.label_12.setText(_translate("inmoovform", "S\n"
"h\n"
"o\n"
"u", None))
        self.labelrrotate.setText(_translate("inmoovform", "90", None))
        self.label_13.setText(_translate("inmoovform", "R\n"
"o\n"
"t", None))
        self.labelrbiceps.setText(_translate("inmoovform", "5", None))
        self.label_14.setText(_translate("inmoovform", "B\n"
" i\n"
"c", None))
        self.labelrpalm.setText(_translate("inmoovform", "0", None))
        self.label_15.setText(_translate("inmoovform", "P\n"
"a\n"
" l\n"
"m", None))
        self.labellomoplate.setText(_translate("inmoovform", "20", None))
        self.labellshoulder.setText(_translate("inmoovform", "30", None))
        self.labelrotate.setText(_translate("inmoovform", "90", None))
        self.labellbiceps.setText(_translate("inmoovform", "5", None))
        self.labellpalm.setText(_translate("inmoovform", "0", None))
        self.label.setText(_translate("inmoovform", "RL Rotate", None))
        self.labelrlrotate.setText(_translate("inmoovform", "90", None))
        self.labeludrotate.setText(_translate("inmoovform", "90", None))
        self.label_19.setText(_translate("inmoovform", "UD Rotate", None))
        self.label_41.setText(_translate("inmoovform", "O\n"
"m\n"
"o", None))
        self.label_42.setText(_translate("inmoovform", "S\n"
"h\n"
"o\n"
"u", None))
        self.label_44.setText(_translate("inmoovform", "R\n"
"o\n"
"t", None))
        self.label_45.setText(_translate("inmoovform", "B\n"
" i\n"
"c", None))
        self.label_43.setText(_translate("inmoovform", "B\n"
" i\n"
"c", None))
        self.label_53.setText(_translate("inmoovform", "Time:", None))
        self.motionTime.setText(_translate("inmoovform", "0.000", None))
        self.scriptName.setText(_translate("inmoovform", "motion1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Control), _translate("inmoovform", "Control", None))
        self.label_68.setText(_translate("inmoovform", "Path:", None))
        self.scriptNew.setText(_translate("inmoovform", "New", None))
        self.scriptRun.setText(_translate("inmoovform", "Run", None))
        self.scriptSave.setText(_translate("inmoovform", "Save...", None))
        self.scriptOpen.setText(_translate("inmoovform", "Open...", None))
        self.scriptClear.setText(_translate("inmoovform", "Clear", None))
        self.appendItem.setText(_translate("inmoovform", "<<", None))
        self.delItemFromMain.setText(_translate("inmoovform", ">>", None))
        self.label_56.setText(_translate("inmoovform", "Delay:", None))
        self.addDelay.setText(_translate("inmoovform", " <<Add Delay", None))
        self.runScriptFromList.setText(_translate("inmoovform", "Run", None))
        self.delMotion.setText(_translate("inmoovform", "Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("inmoovform", "Script", None))
        self.groupBox_9.setTitle(_translate("inmoovform", "Emotion LED", None))
        self.blueText.setText(_translate("inmoovform", "0", None))
        self.redText.setText(_translate("inmoovform", "0", None))
        self.label_46.setText(_translate("inmoovform", "B:", None))
        self.label_40.setText(_translate("inmoovform", "G:", None))
        self.label_39.setText(_translate("inmoovform", "R:", None))
        self.greenText.setText(_translate("inmoovform", "0", None))
        self.label_48.setText(_translate("inmoovform", "G:", None))
        self.label_49.setText(_translate("inmoovform", "B:", None))
        self.rgbOK.setText(_translate("inmoovform", "OK", None))
        self.label_50.setText(_translate("inmoovform", "R:", None))
        self.checkBox_7.setText(_translate("inmoovform", "Right", None))
        self.checkBox_3.setText(_translate("inmoovform", "Left", None))
        self.groupBox_10.setTitle(_translate("inmoovform", "Say", None))
        self.say.setText(_translate("inmoovform", "Say", None))
        self.label_135.setText(_translate("inmoovform", "Language:", None))
        self.sayLang.setItemText(0, _translate("inmoovform", "ru-RU", None))
        self.sayLang.setItemText(1, _translate("inmoovform", "en-EN", None))
        self.label_136.setText(_translate("inmoovform", "Voice:", None))
        self.sayVoice.setItemText(0, _translate("inmoovform", "omazh", None))
        self.sayVoice.setItemText(1, _translate("inmoovform", "jane", None))
        self.sayVoice.setItemText(2, _translate("inmoovform", "zahar", None))
        self.sayVoice.setItemText(3, _translate("inmoovform", "ermil", None))
        self.sayEmotion.setItemText(0, _translate("inmoovform", "good", None))
        self.sayEmotion.setItemText(1, _translate("inmoovform", "neutral", None))
        self.sayEmotion.setItemText(2, _translate("inmoovform", "evil", None))
        self.sayEmotion.setItemText(3, _translate("inmoovform", "mixed", None))
        self.label_137.setText(_translate("inmoovform", "Emotion:", None))
        self.sayOption.setItemText(0, _translate("inmoovform", "normal", None))
        self.sayOption.setItemText(1, _translate("inmoovform", "robot", None))
        self.label_138.setText(_translate("inmoovform", "Option:", None))
        self.saySpeed.setItemText(0, _translate("inmoovform", "1", None))
        self.saySpeed.setItemText(1, _translate("inmoovform", "2", None))
        self.saySpeed.setItemText(2, _translate("inmoovform", "3", None))
        self.saySpeed.setItemText(3, _translate("inmoovform", "4", None))
        self.saySpeed.setItemText(4, _translate("inmoovform", "5", None))
        self.label_139.setText(_translate("inmoovform", "Speed:", None))
        self.groupBox_11.setTitle(_translate("inmoovform", "Singer", None))
        self.singPlay.setText(_translate("inmoovform", "Play", None))
        self.label_54.setText(_translate("inmoovform", "Volume", None))
        self.volume.setText(_translate("inmoovform", "50%", None))
        self.checkBox.setText(_translate("inmoovform", "Background", None))
        self.singSpeedText.setText(_translate("inmoovform", "1", None))
        self.label_70.setText(_translate("inmoovform", "Speed", None))
        self.checkBox_2.setText(_translate("inmoovform", "LED", None))
        self.singOpen.setText(_translate("inmoovform", "Open", None))
        self.label_55.setText(_translate("inmoovform", "Path:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("inmoovform", "Functions", None))
        self.lineRightPort.setText(_translate("inmoovform", "/dev/arduinoHeadMaya", None))
        self.lineHeadPort.setText(_translate("inmoovform", "/dev/arduinoHeadMaya", None))
        self.label_3.setText(_translate("inmoovform", "Port Left:", None))
        self.label_4.setText(_translate("inmoovform", "Port Right:", None))
        self.lineLeftPort.setText(_translate("inmoovform", "/dev/arduinoHeadMaya", None))
        self.label_2.setText(_translate("inmoovform", "Port Head:", None))
        self.label_5.setText(_translate("inmoovform", "IP:", None))
        self.label_47.setText(_translate("inmoovform", "Port:", None))
        self.buttonConnect.setText(_translate("inmoovform", "Connect", None))
        self.buttonDisconnect.setText(_translate("inmoovform", "Disconnect", None))
        self.label_20.setText(_translate("inmoovform", "Status:", None))
        self.connection1.setText(_translate("inmoovform", "lost", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("inmoovform", "Communication", None))
        self.groupBox_3.setTitle(_translate("inmoovform", "Right hand", None))
        self.label_21.setText(_translate("inmoovform", "Palm", None))
        self.label_16.setText(_translate("inmoovform", "Biceps", None))
        self.label_17.setText(_translate("inmoovform", "Rotate", None))
        self.label_18.setText(_translate("inmoovform", "Shoulder", None))
        self.label_7.setText(_translate("inmoovform", "Omoplate", None))
        self.label_8.setText(_translate("inmoovform", "Min", None))
        self.label_9.setText(_translate("inmoovform", "Max", None))
        self.label_22.setText(_translate("inmoovform", "Finger4", None))
        self.label_23.setText(_translate("inmoovform", "Finger5", None))
        self.label_24.setText(_translate("inmoovform", "Finger3", None))
        self.label_10.setText(_translate("inmoovform", "Finger1", None))
        self.label_25.setText(_translate("inmoovform", "Finger2", None))
        self.label_38.setText(_translate("inmoovform", "Str", None))
        self.label_59.setText(_translate("inmoovform", "Pin", None))
        self.groupBox_4.setTitle(_translate("inmoovform", "Left hand", None))
        self.label_26.setText(_translate("inmoovform", "Palm", None))
        self.label_27.setText(_translate("inmoovform", "Biceps", None))
        self.label_28.setText(_translate("inmoovform", "Rotate", None))
        self.label_29.setText(_translate("inmoovform", "Shoulder", None))
        self.label_11.setText(_translate("inmoovform", "Omoplate", None))
        self.label_30.setText(_translate("inmoovform", "Min", None))
        self.label_31.setText(_translate("inmoovform", "Max", None))
        self.label_32.setText(_translate("inmoovform", "Finger4", None))
        self.label_33.setText(_translate("inmoovform", "Finger5", None))
        self.label_34.setText(_translate("inmoovform", "Finger3", None))
        self.label_35.setText(_translate("inmoovform", "Finger1", None))
        self.label_37.setText(_translate("inmoovform", "Finger2", None))
        self.label_57.setText(_translate("inmoovform", "Str", None))
        self.label_60.setText(_translate("inmoovform", "Pin", None))
        self.groupBox_5.setTitle(_translate("inmoovform", "GroupBox", None))
        self.maxMouth.setText(_translate("inmoovform", "000", None))
        self.label_61.setText(_translate("inmoovform", "Str", None))
        self.strRLRotate.setText(_translate("inmoovform", "000", None))
        self.pinUDRotate.setText(_translate("inmoovform", "000", None))
        self.label_62.setText(_translate("inmoovform", "Pin", None))
        self.maxUDRotate.setText(_translate("inmoovform", "000", None))
        self.label_63.setText(_translate("inmoovform", "Mouth", None))
        self.pinRLRotate.setText(_translate("inmoovform", "000", None))
        self.label_64.setText(_translate("inmoovform", "Max", None))
        self.minUDRotate.setText(_translate("inmoovform", "000", None))
        self.pinMouth.setText(_translate("inmoovform", "000", None))
        self.strMouth.setText(_translate("inmoovform", "000", None))
        self.label_65.setText(_translate("inmoovform", "UDRotate", None))
        self.label_66.setText(_translate("inmoovform", "LRRotate", None))
        self.label_67.setText(_translate("inmoovform", "Min", None))
        self.minRLRotate.setText(_translate("inmoovform", "000", None))
        self.strUDRotate.setText(_translate("inmoovform", "000", None))
        self.minMouth.setText(_translate("inmoovform", "000", None))
        self.maxRLRotate.setText(_translate("inmoovform", "000", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("inmoovform", "Servo", None))
        self.seveSettings.setText(_translate("inmoovform", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("inmoovform", "Settings", None))
        self.menu1.setTitle(_translate("inmoovform", "File", None))
        self.menuScript.setTitle(_translate("inmoovform", "Script", None))
        self.menuHelp.setTitle(_translate("inmoovform", "Help", None))
        self.action1.setText(_translate("inmoovform", "Open Settings...", None))
        self.actionExit.setText(_translate("inmoovform", "Exit", None))
        self.actionSave_Sattings_As.setText(_translate("inmoovform", "Save Sattings As...", None))
        self.actionOpen_Script.setText(_translate("inmoovform", "Open...", None))
        self.actionAbuot.setText(_translate("inmoovform", "Abuot", None))
        self.actionSite.setText(_translate("inmoovform", "Site", None))
        self.actionCheck_for_Update.setText(_translate("inmoovform", "Check for Update...", None))
        self.actionSave.setText(_translate("inmoovform", "Save...", None))
        self.actionReference.setText(_translate("inmoovform", "Reference", None))

